name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.base.svg
          user: IndAlok
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_lines: yes
          plugin_traffic: yes

      - name: Achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.achievements.svg
          user: IndAlok
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: X
          plugin_achievements_secrets: yes

      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.languages.svg
          user: IndAlok
          base: ""
          plugin_languages: yes
          plugin_languages_details: lines, percentage
          plugin_languages_sections: most-used
          plugin_languages_limit: 8

      - name: Habits
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.habits.svg
          user: IndAlok
          base: ""
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 365
          plugin_habits_facts: no
          plugin_habits_charts: yes

      - name: IsoCalendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.iso.svg
          user: IndAlok
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

  generate-snake:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: IndAlok
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: push snake
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
